### ISSUE TITLE
Time series regression?

### ISSUE THREAD

**Issue by wangy8989** [automl/TabPFN#23]
Hi, I am also very looking forward to use TabPFN for regression tasks.
However, I am also wondering if TabPFN can be modified to do time series prediction?
My goal is to do time series regression in finance.
Thanks!

**Comment by arnaudlenain** [comment]
> 
This is not an issue with implementation of the code. 
Also when people provide such an amazing tool, we begin by saying thank and we don't ask them to do our job before thanking them.

**Comment by noahho** [comment]
Hi Yicheng,
We believe it would be. You could add the time variable as just another variable into the classification tasks or create a prior that is customized to time series regression. Using the PFN technique it would be possible to taylor a predictor to the time domain, encoding your specific prior on how the time variable behaves into the prior. This would surely be very interesting.
Best,
Noah

**Comment by wangy8989** [comment]
Thank you so much for answering!

**Comment by wangy8989** [comment]
@noahho I do have another question about the regression task. Why is generalizing to regressions more difficult? 
Naively, I would think it is straight forward:  
Adjustment 1: for the prior data, just replace classification by regression, e.g. change class assigner to RegressionNormalized().
Adjustment 2:  adjust the objective function (replace log loss by MSE).  
Thanks!

**Comment by noahho** [comment]
Hi Wang! 

You are completely right - a lot of the code is there already. We have made good progress on this as well and hope to share soon. It turns out to be harder, because of the often unnormalized y labels. I.e. some targets follow an exponential distribution. This is hard to predict with our way of quantizing prediction buckets, because there will be a very low quantization level within this target range.
