### ISSUE TITLE
transformer architecture

### ISSUE THREAD

**Issue by wangy8989** [automl/TabPFN#93]
about why adding the embeddings of x and y together
    on line 132 of transformer.py: train_x = x_src[:single_eval_pos] + y_src[:single_eval_pos]
    It seems that you are adding the x and y embeddings element-wise, each with shape torch.Size([single_eval_pos, batch_size, emsize]).
    Why would you add a feature together with a target? But not a concatenation?

Thanks for your time answering!

**Comment by noahho** [comment]
Hi! Please apologize the late reply!

Adding the embeddings (x_src + y_src) instead of concatenating them is an architectural choice inspired by how transformers handle positional encodings. The key benefits are:

The model learns to encode x and y information in complementary "regions" of the same embedding space, allowing efficient use of the available dimensions
Addition preserves the embedding dimension, requiring fewer parameters in subsequent layers compared to concatenation
The transformer's self-attention mechanism is very effective at disentangling the combined signals during processing

While concatenation would also work, addition provides a more parameter-efficient solution without loss of expressiveness.
